# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: My-Shop-Api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  memorySize: 2048
  region: us-east-1
functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGOOSE_URL: mongodb+srv://aritra1521:zoxdoB-5koppa-gugwef@cluster0.ust1u.mongodb.net/my_store?retryWrites=true&w=majority
      JWT_SECRET: it-is-very-secure-long-thing
      JWT_EXPIRES_IN: 90d
      RAZORPAY_KEY_ID: rzp_test_ftb5flv3icVffB
      RAZOR_PAY_KEY_SECRET: 9CIn2hbt4BD0c8OiR1LCNnKS
package:
  include:
    - dist/**
    - handler.js
    - package.json
